(function () {
  "use strict";

  App.stores.countyStore = new Ext.data.JsonStore({
    model: 'County',
    data: [{
      value: 'Carlow',
      text: 'Carlow'
    }, {
      value: 'Cavan',
      text: 'Cavan'
    }, {
      value: 'Clare',
      text: 'Clare'
    }, {
      value: 'Cork',
      text: 'Cork'
    }, {
      value: 'Donegal',
      text: 'Donegal'
    }, {
      value: 'Dublin',
      text: 'Dublin'
    }, {
      value: 'Galway',
      text: 'Galway'
    }, {
      value: 'Kerry',
      text: 'Kerry'
    }, {
      value: 'Kildare',
      text: 'Kildare'
    }, {
      value: 'Kilkenny',
      text: 'Kilkenny'
    }, {
      value: 'Laois',
      text: 'Laois'
    }, {
      value: 'Leitrim',
      text: 'Leitrim'
    }, {
      value: 'Limerick',
      text: 'Limerick'
    }, {
      value: 'Longford',
      text: 'Longford'
    }, {
      value: 'Louth',
      text: 'Louth'
    }, {
      value: 'Mayo',
      text: 'Mayo'
    }, {
      value: 'Meath',
      text: 'Meath'
    }, {
      value: 'Monaghan',
      text: 'Monaghan'
    }, {
      value: 'Offaly',
      text: 'Offaly'
    }, {
      value: 'Roscommon',
      text: 'Roscommon'
    }, {
      value: 'Sligo',
      text: 'Sligo'
    }, {
      value: 'Tipperary',
      text: 'Tipperary'
    }, {
      value: 'Waterford',
      text: 'Waterford'
    }, {
      value: 'Westmeath',
      text: 'Westmeath'
    }, {
      value: 'Wexford',
      text: 'Wexford'
    }, {
      value: 'Wicklow',
      text: 'Wicklow'
    }]
  });
  
}());